---
# Common params which are applicable to environment
#httpProxy: 
#httpsProxy: 
#noProxy: .local
vsphere:
  vcenter: vcsnsx-vc.infra.demo.redhat.com
  datacenter: SDDC-Datacenter
  cluster: /SDDC-Datacenter/host/Cluster-1
  datastore: /SDDC-Datacenter/datastore/workload_share_dwPsq
  network: segment-sandbox-gtwdl
  folder: /SDDC-Datacenter/vm/Workloads/sandbox-gtwdl
  username: "{{ vsphere_username | default('changeme') }}"
  password: "{{ vsphere_password | default('changeme') }}"

# Cluster list and specific params
openshift_clusters:
  - name: p488w
    baseDomain: dynamic.opentlc.com
    networking:
      clusterNetworkcidr: 172.16.0.0/16
      machineNetworkcidr: 192.168.18.0/24
      serviceNetworkcidr: 172.17.0.0/16
    platform:
      apiVIP: 192.168.18.201
      ingressVIP: 192.168.18.202
    controlplane:
      replicas: 3
      cpus: 8
      ram: 16384
      disksizeGB: 120
    compute:
      replicas: 3
      cpus: 12
      ram: 32768
      disksizeGB: 120

additionalTrustBundlePolicy: Proxyonly
additionalTrustBundle: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
