---
bastion_pkgs_install:
  - jq
  - vim
  - vim-enhanced
  - tree
  - tmux
  - wget
  - curl
  - ansible-core
  - nmap
  - nmap-ncat
  - bash-completion
  - git
  - podman
  - skopeo
bastion_openshift_version: "{{ openshift_version | default('latest') }}"
bastion_openshift_client_url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ bastion_openshift_version }}/openshift-client-linux.tar.gz"
bastion_openshift_installer_url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ bastion_openshift_version }}/openshift-install-linux.tar.gz"
